name: opencpn
version: '4.8+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Open Chart Plotter Navigator
description: |
  OpenCPN (Open Chart Plotter Navigator) is a free software project to create
  a concise chart plotter and navigation software, for use underway or as
  a planning tool. OpenCPN is developed by a team of active sailors using real
  world conditions for program testing and refinement.

grade: devel # must be 'stable' to release into candidate/stable channels

confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  opencpn:
    command: desktop-launch opencpn
    plugs: [network, network-bind, home, opengl, x11]
    environment:
      WX_OPENCPN_DATA_DIR: $SNAP/usr/share/opencpn/

parts:
  opencpn:
    plugin: cmake
    source: https://github.com/OpenCPN/OpenCPN.git
    source-type: git
    source-depth: 1
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/snap/opencpn/current/usr
    build-packages:
      - gettext
      - libgps-dev
      - wx-common
      - libwxgtk3.0-dev
      - libglu1-mesa-dev
      - libgtk2.0-dev
      - wx3.0-headers
      - libbz2-dev
      - libtinyxml-dev
      - libcurl4-openssl-dev
      - libexpat1-dev
      - libcairo2-dev
    after:
      - desktop-gtk2
    organize:
      snap/opencpn/current/usr : usr/
